// ---------------------------------------------------------------------------
// DEMO CATALOG SEED SCRIPT
// Run with: npx tsx src/db/seed.ts
// Populates the products / reviews / coupons tables with realistic sample
// data for the FlowForge AI marketplace MVP.
// ---------------------------------------------------------------------------
import { db, pool } from "./index";
import { products, reviews, coupons } from "./schema";
import { sql } from "drizzle-orm";

type SeedProduct = typeof products.$inferInsert & {
  reviewSeed: { author: string; role: string; rating: number; comment: string }[];
};

const images = ["cyan", "violet", "indigo", "teal"] as const;

const catalog: SeedProduct[] = [
  {
    slug: "ai-whatsapp-lead-qualifier",
    name: "AI WhatsApp Lead Qualifier",
    tagline: "Capture, qualify, and route WhatsApp leads with AI in real time.",
    description:
      "Most businesses lose warm WhatsApp leads because nobody replies fast enough or asks the right qualifying questions. This workflow listens for incoming WhatsApp messages, uses an AI agent to understand intent, scores the lead against your criteria, and instantly pushes qualified prospects into your CRM while notifying your sales team on Slack. Cold or irrelevant messages are politely filtered out, so your team only spends time on leads worth chasing.",
    category: "WhatsApp Automation",
    tags: ["AI", "WhatsApp", "Leads", "CRM"],
    price: 4990,
    oldPrice: 7500,
    rating: "4.9",
    reviewsCount: 128,
    salesCount: 1248,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "20 minutes",
    version: "2.3.0",
    creator: "FlowForge Studio",
    featured: true,
    bestseller: true,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "cyan",
    features: [
      "Understands intent from free-text WhatsApp messages",
      "Scores leads Hot / Warm / Cold automatically",
      "Pushes qualified leads straight into your CRM",
      "Sends real-time Slack alerts to your sales team",
      "Auto-replies to unqualified leads with a polite message",
    ],
    requirements: ["WhatsApp Business API or Twilio account", "CRM API key (HubSpot / Pipedrive / Sheets)", "OpenAI API key"],
    setupSteps: [
      "Import the workflow JSON into your n8n instance",
      "Connect your WhatsApp Business / Twilio credentials",
      "Add your OpenAI API key in the credentials panel",
      "Map your CRM fields inside the CRM node",
      "Activate the workflow and send a test message",
    ],
    included: [
      { name: "AI-WhatsApp-Lead-Qualifier.json", type: "n8n workflow" },
      { name: "Setup & credentials guide (PDF)", type: "guide" },
      { name: "Prompt template pack", type: "prompts" },
    ],
    workflowSteps: ["WhatsApp Trigger", "AI Intent Agent", "Lead Scoring", "CRM Sync", "Slack Alert"],
    faq: [
      { q: "Does this work with the official WhatsApp Business API?", a: "Yes, it supports both the official Cloud API and Twilio's WhatsApp sandbox/production numbers." },
      { q: "Can I change the qualifying questions?", a: "Yes, the AI prompt is fully editable inside the AI Agent node." },
    ],
    reviewSeed: [
      { author: "Bilal Ahmed", role: "Agency Owner", rating: 5, comment: "Cut our WhatsApp response time from hours to seconds. Leads are pre-qualified before my team even looks at them." },
      { author: "Ayesha Raza", role: "Founder", rating: 5, comment: "Setup guide was clear even though I'm not technical. Running in production after one afternoon." },
    ],
  },
  {
    slug: "ai-customer-support-agent",
    name: "AI Customer Support Agent",
    tagline: "A tireless AI support rep that resolves tickets across email and chat.",
    description:
      "Give your customers instant, accurate answers around the clock. This AI agent reads incoming support tickets or chat messages, searches your knowledge base, drafts a helpful response, and either sends it automatically for simple queries or hands off complex issues to a human with full context attached. It reduces first-response time dramatically while keeping your team in control of edge cases.",
    category: "AI Agents",
    tags: ["AI", "Support", "Customer Service", "Helpdesk"],
    price: 6990,
    oldPrice: 9990,
    rating: "4.8",
    reviewsCount: 96,
    salesCount: 864,
    difficulty: "Intermediate",
    compatibility: "n8n",
    setupTime: "35 minutes",
    version: "1.8.2",
    creator: "FlowForge Studio",
    featured: true,
    bestseller: true,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "violet",
    features: [
      "Reads and understands incoming support tickets",
      "Searches your help docs / knowledge base automatically",
      "Drafts on-brand replies using your tone of voice",
      "Escalates complex tickets to a human with a full summary",
      "Works with Zendesk, Gmail, and Intercom-style inboxes",
    ],
    requirements: ["Helpdesk or inbox API access", "OpenAI or Claude API key", "Knowledge base (Notion, Google Docs, or vector store)"],
    setupSteps: [
      "Import the workflow into n8n",
      "Connect your helpdesk/inbox credentials",
      "Point the agent to your knowledge base source",
      "Configure escalation rules",
      "Test with sample tickets before going live",
    ],
    included: [
      { name: "AI-Support-Agent.json", type: "n8n workflow" },
      { name: "Knowledge base connector guide", type: "guide" },
      { name: "Escalation rules template", type: "template" },
    ],
    workflowSteps: ["Ticket Trigger", "Knowledge Search", "AI Agent Draft", "Confidence Check", "Auto-Reply / Escalate"],
    faq: [
      { q: "Can it use our existing help center articles?", a: "Yes, connect Notion, Google Docs, or a vector database and the agent will search it before replying." },
      { q: "What happens if the AI is unsure?", a: "Tickets below the confidence threshold are automatically escalated to a human agent with full context." },
    ],
    reviewSeed: [
      { author: "Hamza Tariq", role: "Automation Consultant", rating: 5, comment: "Deflected almost 40% of our tier-1 tickets in the first week." },
      { author: "Sana Malik", role: "Marketing Manager", rating: 4, comment: "Great out of the box, tuned the prompt a little for our tone of voice." },
    ],
  },
  {
    slug: "automated-email-follow-up",
    name: "Automated Email Follow-Up",
    tagline: "Never let a cold lead go quiet again with AI-timed follow-up sequences.",
    description:
      "Turns silence into replies. This workflow tracks whether a prospect opened or responded to your email, then uses AI to draft a contextual, non-pushy follow-up at the ideal moment. Sequences stop automatically the moment someone replies, so nobody gets a robotic email after they've already responded.",
    category: "Sales Automation",
    tags: ["Email", "Follow-up", "Sales", "AI"],
    price: 3490,
    oldPrice: 4990,
    rating: "4.7",
    reviewsCount: 74,
    salesCount: 612,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "15 minutes",
    version: "1.4.0",
    creator: "FlowForge Studio",
    featured: true,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "cyan",
    features: [
      "Tracks opens and replies automatically",
      "AI drafts context-aware follow-up copy",
      "Smart send-time optimization",
      "Automatically stops when a reply is detected",
      "Works with Gmail, Outlook and SMTP",
    ],
    requirements: ["Gmail/Outlook API or SMTP credentials", "OpenAI API key"],
    setupSteps: [
      "Import workflow JSON",
      "Connect your email account",
      "Set your follow-up cadence (e.g. 2, 4, 7 days)",
      "Add your OpenAI key for AI-drafted copy",
      "Launch your first sequence",
    ],
    included: [
      { name: "Email-Follow-Up.json", type: "n8n workflow" },
      { name: "Follow-up copy prompt pack", type: "prompts" },
    ],
    workflowSteps: ["Email Sent Trigger", "Reply Detector", "Wait/Delay", "AI Draft Follow-up", "Send Email"],
    faq: [
      { q: "Will it keep emailing after someone replies?", a: "No. The reply detector immediately halts the sequence for that contact." },
    ],
    reviewSeed: [
      { author: "Usman Sheikh", role: "Freelancer", rating: 5, comment: "Simple to set up and my reply rate went up noticeably." },
    ],
  },
  {
    slug: "ai-content-factory",
    name: "AI Content Factory",
    tagline: "Turn one idea into a week of on-brand social and blog content.",
    description:
      "Feed this workflow a topic or a long-form article and it produces a full content package: a blog post outline, five social captions, a newsletter blurb, and relevant hashtags — all matched to your brand voice. Ideal for solo founders and marketing teams who need consistent output without a full content team.",
    category: "Content Automation",
    tags: ["AI", "Content", "Marketing", "Social Media"],
    price: 5990,
    oldPrice: 8500,
    rating: "4.8",
    reviewsCount: 143,
    salesCount: 981,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "20 minutes",
    version: "3.1.0",
    creator: "FlowForge Studio",
    featured: true,
    bestseller: true,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "violet",
    features: [
      "Generates blog outlines and full drafts",
      "Creates 5+ social captions per topic",
      "Matches your defined brand voice",
      "Outputs hashtags and SEO keywords",
      "Publishes drafts directly to Notion or Google Docs",
    ],
    requirements: ["OpenAI API key", "Notion or Google Docs API access"],
    setupSteps: [
      "Import the workflow",
      "Define your brand voice in the config node",
      "Connect Notion/Google Docs for output",
      "Trigger with a topic or URL",
    ],
    included: [
      { name: "AI-Content-Factory.json", type: "n8n workflow" },
      { name: "Brand voice prompt template", type: "prompts" },
    ],
    workflowSteps: ["Topic Input", "AI Research", "AI Draft Generator", "Brand Voice Filter", "Publish to Notion"],
    faq: [
      { q: "Can I control tone and style?", a: "Yes, the brand voice node lets you define tone, style, and banned words." },
    ],
    reviewSeed: [
      { author: "Fatima Noor", role: "Marketing Manager", rating: 5, comment: "Saved our team roughly 6 hours a week on content drafts." },
    ],
  },
  {
    slug: "crm-lead-enrichment",
    name: "CRM Lead Enrichment",
    tagline: "Auto-enrich every new CRM lead with company and contact data.",
    description:
      "The moment a new lead lands in your CRM, this workflow enriches it with company size, industry, social profiles, and a personalized AI-generated icebreaker line — giving your sales reps everything they need before the first call.",
    category: "Sales Automation",
    tags: ["CRM", "Lead Enrichment", "Sales", "AI"],
    price: 4490,
    oldPrice: null,
    rating: "4.7",
    reviewsCount: 58,
    salesCount: 402,
    difficulty: "Intermediate",
    compatibility: "n8n",
    setupTime: "25 minutes",
    version: "1.6.0",
    creator: "FlowForge Studio",
    featured: true,
    bestseller: false,
    isFree: false,
    onSale: false,
    isNew: false,
    image: "indigo",
    features: [
      "Enriches leads with firmographic + social data",
      "Generates a personalized AI icebreaker per lead",
      "Updates CRM fields automatically",
      "Flags high-value accounts for priority outreach",
    ],
    requirements: ["CRM API key", "Data enrichment API (Clearbit/Apollo-style)", "OpenAI API key"],
    setupSteps: ["Import workflow", "Connect CRM + enrichment API", "Configure icebreaker prompt", "Activate trigger on new lead"],
    included: [{ name: "CRM-Lead-Enrichment.json", type: "n8n workflow" }, { name: "Field mapping guide", type: "guide" }],
    workflowSteps: ["New Lead Trigger", "Enrichment API", "AI Icebreaker", "CRM Update", "Priority Flag"],
    faq: [{ q: "Which CRMs are supported?", a: "HubSpot, Pipedrive, and any CRM with a REST API or native n8n node." }],
    reviewSeed: [{ author: "Zara Iqbal", role: "Agency Owner", rating: 4, comment: "Great time saver for our SDR team, easy to customize fields." }],
  },
  {
    slug: "ai-invoice-processor",
    name: "AI Invoice Processor",
    tagline: "Extract, validate, and sync invoice data without manual entry.",
    description:
      "Stop retyping invoice data. This workflow watches an inbox or folder for incoming invoices, uses AI to extract line items, totals, and vendor details, validates them against your rules, and syncs clean records into your accounting software or spreadsheet.",
    category: "Business Automation",
    tags: ["AI", "Invoices", "Finance", "PDF"],
    price: 5490,
    oldPrice: 7990,
    rating: "4.6",
    reviewsCount: 41,
    salesCount: 318,
    difficulty: "Intermediate",
    compatibility: "n8n",
    setupTime: "30 minutes",
    version: "1.2.0",
    creator: "FlowForge Studio",
    featured: true,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "teal",
    features: [
      "Extracts vendor, line items, tax, and totals from PDFs",
      "Validates totals and flags mismatches",
      "Syncs clean data to Sheets/QuickBooks-style tools",
      "Archives original files automatically",
    ],
    requirements: ["Email/Drive access", "OpenAI API key (vision-capable)", "Accounting tool API (optional)"],
    setupSteps: ["Import workflow", "Connect inbox/drive folder", "Configure validation rules", "Connect accounting export target"],
    included: [{ name: "AI-Invoice-Processor.json", type: "n8n workflow" }, { name: "Validation rules template", type: "template" }],
    workflowSteps: ["Invoice Received", "AI Data Extraction", "Validation", "Accounting Sync", "Archive"],
    faq: [{ q: "Does it work with scanned/photo invoices?", a: "Yes, the AI extraction node supports image and scanned PDF inputs." }],
    reviewSeed: [{ author: "Ali Raza", role: "Founder", rating: 5, comment: "Removed a full day of manual bookkeeping every month." }],
  },
  {
    slug: "youtube-content-automation",
    name: "YouTube Content Automation",
    tagline: "Turn long-form videos into titles, descriptions, chapters, and clips ideas.",
    description:
      "Feed this workflow a YouTube video link or transcript and receive SEO-optimized titles, a full description, timestamped chapters, and a list of short-form clip ideas — ready to paste in or hand to an editor.",
    category: "Content Automation",
    tags: ["YouTube", "Content", "AI", "SEO"],
    price: 3990,
    oldPrice: 5490,
    rating: "4.7",
    reviewsCount: 65,
    salesCount: 455,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "15 minutes",
    version: "1.3.0",
    creator: "FlowForge Studio",
    featured: true,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "cyan",
    features: [
      "Generates SEO-friendly titles and descriptions",
      "Creates timestamped chapters automatically",
      "Suggests short-form clip moments",
      "Outputs directly to Notion or Sheets",
    ],
    requirements: ["YouTube Data API key (optional)", "OpenAI API key"],
    setupSteps: ["Import workflow", "Add YouTube link or transcript source", "Connect OpenAI key", "Review generated output"],
    included: [{ name: "YouTube-Content-Automation.json", type: "n8n workflow" }],
    workflowSteps: ["Video/Transcript Input", "AI Summarizer", "Chapter Generator", "Clip Idea Generator", "Export"],
    faq: [{ q: "Do I need the raw transcript?", a: "The workflow can auto-fetch captions from YouTube or accept a pasted transcript." }],
    reviewSeed: [{ author: "Nabeel Chaudhry", role: "Freelancer", rating: 5, comment: "My weekly upload prep time dropped from 2 hours to 15 minutes." }],
  },
  {
    slug: "ai-research-agent",
    name: "AI Research Agent",
    tagline: "An autonomous agent that researches any topic and returns a structured brief.",
    description:
      "Give the agent a research question and it searches the web, reads multiple sources, cross-checks facts, and compiles a structured summary with citations — perfect for market research, competitor analysis, or content research.",
    category: "AI Agents",
    tags: ["AI", "Research", "Agent", "Web Search"],
    price: 6490,
    oldPrice: null,
    rating: "4.9",
    reviewsCount: 87,
    salesCount: 540,
    difficulty: "Advanced",
    compatibility: "n8n",
    setupTime: "40 minutes",
    version: "2.0.0",
    creator: "FlowForge Studio",
    featured: true,
    bestseller: true,
    isFree: false,
    onSale: false,
    isNew: false,
    image: "violet",
    features: [
      "Multi-source autonomous web research",
      "Fact cross-checking across sources",
      "Structured brief with citations",
      "Configurable depth and source count",
    ],
    requirements: ["Search API (SerpAPI/Bing)", "OpenAI or Claude API key"],
    setupSteps: ["Import workflow", "Connect search API", "Connect LLM API key", "Run with a research question"],
    included: [{ name: "AI-Research-Agent.json", type: "n8n workflow" }, { name: "Research brief template", type: "template" }],
    workflowSteps: ["Question Input", "Web Search", "Source Reader Agent", "Fact Cross-check", "Structured Brief"],
    faq: [{ q: "How many sources does it check?", a: "Configurable — default is 6 to 10 sources per research question." }],
    reviewSeed: [{ author: "Hira Farooq", role: "Automation Consultant", rating: 5, comment: "Genuinely feels like having a junior research analyst on call." }],
  },
  {
    slug: "shopify-order-automation",
    name: "Shopify Order Automation",
    tagline: "Sync orders, update inventory, and notify customers automatically.",
    description:
      "Connects your Shopify store to fulfillment, inventory, and customer notifications. Every new order updates stock levels, creates a fulfillment task, and sends a friendly status update to the customer — reducing manual order-ops work to zero.",
    category: "Business Automation",
    tags: ["Shopify", "E-commerce", "Orders", "Automation"],
    price: 4990,
    oldPrice: 6990,
    rating: "4.6",
    reviewsCount: 52,
    salesCount: 376,
    difficulty: "Intermediate",
    compatibility: "n8n",
    setupTime: "25 minutes",
    version: "1.5.0",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "indigo",
    features: [
      "Auto-updates inventory across channels",
      "Creates fulfillment tasks instantly",
      "Sends branded order status emails/SMS",
      "Flags low-stock items automatically",
    ],
    requirements: ["Shopify Admin API key", "Notification channel (Email/SMS)"],
    setupSteps: ["Import workflow", "Connect Shopify store", "Configure fulfillment rules", "Enable customer notifications"],
    included: [{ name: "Shopify-Order-Automation.json", type: "n8n workflow" }],
    workflowSteps: ["Order Created", "Inventory Update", "Fulfillment Task", "Customer Notification", "Low-Stock Alert"],
    faq: [{ q: "Does it support multiple stores?", a: "Yes, duplicate the workflow per store or parameterize the store credential." }],
    reviewSeed: [{ author: "Omar Sultan", role: "Founder", rating: 4, comment: "Solid workflow, took a bit of tuning for our custom fulfillment steps." }],
  },
  {
    slug: "ai-proposal-generator",
    name: "AI Proposal Generator",
    tagline: "Generate client-ready proposals in minutes from a short brief.",
    description:
      "Turn a short project brief into a polished, branded proposal document — scope, timeline, pricing tiers, and terms included. Great for agencies and freelancers who need to send proposals fast without starting from a blank page each time.",
    category: "Sales Automation",
    tags: ["AI", "Proposals", "Sales", "Agency"],
    price: 3990,
    oldPrice: 5990,
    rating: "4.8",
    reviewsCount: 69,
    salesCount: 289,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "15 minutes",
    version: "1.1.0",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: true,
    image: "cyan",
    features: [
      "Generates scope, timeline, and pricing sections",
      "Uses your branded proposal template",
      "Exports to PDF or Google Docs",
      "Personalizes tone based on client industry",
    ],
    requirements: ["OpenAI API key", "Google Docs or PDF export access"],
    setupSteps: ["Import workflow", "Upload your proposal template", "Connect export destination", "Trigger with a project brief"],
    included: [{ name: "AI-Proposal-Generator.json", type: "n8n workflow" }, { name: "Proposal template", type: "template" }],
    workflowSteps: ["Brief Input", "AI Section Generator", "Pricing Builder", "Template Merge", "Export PDF"],
    faq: [{ q: "Can I use my own template design?", a: "Yes, upload your branded template and the workflow fills it in automatically." }],
    reviewSeed: [{ author: "Danish Aslam", role: "Agency Owner", rating: 5, comment: "Proposal turnaround went from a day to under 20 minutes." }],
  },
  {
    slug: "instagram-content-scheduler",
    name: "Instagram Content Scheduler",
    tagline: "AI-planned captions and a scheduled posting pipeline for Instagram.",
    description:
      "Plan a week of Instagram content in one sitting. This workflow generates on-brand captions and hashtag sets from your content calendar, then schedules posts automatically at your optimal engagement times.",
    category: "Marketing Automation",
    tags: ["Instagram", "Social Media", "Content", "AI"],
    price: 3490,
    oldPrice: null,
    rating: "4.5",
    reviewsCount: 38,
    salesCount: 210,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "15 minutes",
    version: "1.0.4",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: false,
    isNew: true,
    image: "violet",
    features: [
      "AI-generated captions and hashtags",
      "Optimal time scheduling",
      "Content calendar sync (Sheets/Notion)",
      "Auto-posts image and reel content",
    ],
    requirements: ["Instagram Graph API access", "OpenAI API key"],
    setupSteps: ["Import workflow", "Connect Instagram business account", "Connect content calendar", "Set posting schedule"],
    included: [{ name: "Instagram-Scheduler.json", type: "n8n workflow" }],
    workflowSteps: ["Content Calendar", "AI Caption Generator", "Hashtag Builder", "Schedule Queue", "Auto-Publish"],
    faq: [{ q: "Does it support Reels?", a: "Yes, both feed posts and Reels are supported through the Graph API." }],
    reviewSeed: [{ author: "Mahnoor Sheikh", role: "Freelancer", rating: 4, comment: "Great for batching a week of posts on a Sunday." }],
  },
  {
    slug: "ai-pdf-data-extractor",
    name: "AI PDF Data Extractor",
    tagline: "Pull structured data out of any PDF — contracts, forms, reports.",
    description:
      "Drop in any PDF and get clean structured JSON or spreadsheet rows out. Handles contracts, application forms, and reports by using AI to understand layout and context rather than rigid templates.",
    category: "Developer Automation",
    tags: ["AI", "PDF", "Data Extraction", "Automation"],
    price: 4490,
    oldPrice: 5990,
    rating: "4.6",
    reviewsCount: 33,
    salesCount: 188,
    difficulty: "Intermediate",
    compatibility: "n8n",
    setupTime: "20 minutes",
    version: "1.2.1",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "indigo",
    features: [
      "Layout-aware AI extraction (not rigid templates)",
      "Outputs clean JSON or spreadsheet rows",
      "Handles multi-page documents",
      "Confidence scoring per field",
    ],
    requirements: ["OpenAI API key (vision-capable)", "Storage destination (Sheets/DB)"],
    setupSteps: ["Import workflow", "Configure the fields you need extracted", "Connect output destination", "Test with a sample PDF"],
    included: [{ name: "AI-PDF-Extractor.json", type: "n8n workflow" }],
    workflowSteps: ["PDF Upload", "Layout Analysis", "AI Field Extraction", "Confidence Check", "Export to Sheet/DB"],
    faq: [{ q: "Can it handle handwritten forms?", a: "Clear handwriting is often extracted successfully, though print text yields the highest accuracy." }],
    reviewSeed: [{ author: "Talha Farooq", role: "Automation Consultant", rating: 4, comment: "Very flexible for varied contract layouts." }],
  },
  {
    slug: "google-sheets-ai-assistant",
    name: "Google Sheets AI Assistant",
    tagline: "Ask questions about your spreadsheet data in plain English.",
    description:
      "Connects an AI assistant directly to your Google Sheet. Type a question like 'which region had the highest sales last month' and get an instant, accurate answer — no formulas required.",
    category: "Developer Automation",
    tags: ["Google Sheets", "AI", "Data", "Free"],
    price: 0,
    oldPrice: null,
    rating: "4.7",
    reviewsCount: 152,
    salesCount: 2210,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "10 minutes",
    version: "1.0.0",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: true,
    onSale: false,
    isNew: false,
    image: "teal",
    features: [
      "Ask spreadsheet questions in plain English",
      "Works with any Google Sheet structure",
      "Returns explanations, not just numbers",
      "No coding required",
    ],
    requirements: ["Google Sheets API access", "OpenAI API key"],
    setupSteps: ["Import workflow", "Connect your Google account", "Point to your sheet", "Start asking questions"],
    included: [{ name: "Sheets-AI-Assistant.json", type: "n8n workflow" }],
    workflowSteps: ["Question Input", "Sheet Data Fetch", "AI Analysis", "Answer Output"],
    faq: [{ q: "Is this really free?", a: "Yes, this is one of our free demo workflows to help you get started with n8n + AI." }],
    reviewSeed: [{ author: "Kamran Yousuf", role: "Freelancer", rating: 5, comment: "Great free starter workflow, easy to extend." }],
  },
  {
    slug: "ai-meeting-summary-workflow",
    name: "AI Meeting Summary Workflow",
    tagline: "Turn meeting recordings into summaries, decisions, and action items.",
    description:
      "Automatically transcribes meeting recordings and produces a clean summary with key decisions, owners, and action items — then distributes it to attendees via email or Slack.",
    category: "Business Automation",
    tags: ["AI", "Meetings", "Productivity", "Slack"],
    price: 2990,
    oldPrice: 4490,
    rating: "4.7",
    reviewsCount: 44,
    salesCount: 301,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "15 minutes",
    version: "1.1.0",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "cyan",
    features: [
      "Auto-transcribes meeting audio/video",
      "Extracts decisions and action items",
      "Assigns owners automatically where mentioned",
      "Distributes summary via email/Slack",
    ],
    requirements: ["Transcription API (Whisper-compatible)", "OpenAI API key"],
    setupSteps: ["Import workflow", "Connect recording source (Zoom/Drive)", "Connect distribution channel", "Activate"],
    included: [{ name: "AI-Meeting-Summary.json", type: "n8n workflow" }],
    workflowSteps: ["Recording Trigger", "Transcription", "AI Summarizer", "Action Item Extractor", "Distribute"],
    faq: [{ q: "Which meeting tools are supported?", a: "Zoom, Google Meet recordings, and any audio file dropped into a watched folder." }],
    reviewSeed: [{ author: "Rida Kamal", role: "Marketing Manager", rating: 5, comment: "Our team finally has consistent meeting notes without manual effort." }],
  },
  {
    slug: "lead-scraping-enrichment",
    name: "Lead Scraping & Enrichment",
    tagline: "Build a targeted lead list and enrich it automatically.",
    description:
      "Scrapes public business directories/search results based on your target criteria, then enriches each lead with contact and firmographic data, producing a ready-to-use outreach list.",
    category: "Sales Automation",
    tags: ["Lead Generation", "Scraping", "Sales", "AI"],
    price: 5490,
    oldPrice: 7990,
    rating: "4.6",
    reviewsCount: 47,
    salesCount: 265,
    difficulty: "Advanced",
    compatibility: "n8n",
    setupTime: "35 minutes",
    version: "1.4.2",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "violet",
    features: [
      "Targeted scraping by industry/location",
      "Automatic contact + firmographic enrichment",
      "Deduplication and validation",
      "Exports ready-to-use outreach list",
    ],
    requirements: ["Scraping/search API", "Data enrichment API", "Google Sheets or CRM destination"],
    setupSteps: ["Import workflow", "Configure target search criteria", "Connect enrichment API", "Export to your CRM/Sheet"],
    included: [{ name: "Lead-Scraping-Enrichment.json", type: "n8n workflow" }],
    workflowSteps: ["Search Criteria", "Scraper", "Enrichment API", "Deduplication", "Export List"],
    faq: [{ q: "Is scraping compliant?", a: "The workflow only targets public directory data; always confirm compliance with target sites' terms." }],
    reviewSeed: [{ author: "Faizan Iqbal", role: "Agency Owner", rating: 4, comment: "Built us a 500-lead list in an afternoon with clean enrichment." }],
  },
  {
    slug: "ai-review-response-automation",
    name: "AI Review Response Automation",
    tagline: "Reply to every customer review with a thoughtful, on-brand response.",
    description:
      "Monitors Google, Facebook, and marketplace reviews, drafts a personalized on-brand reply for each one, and either auto-posts positive review replies or queues sensitive ones for your approval.",
    category: "Marketing Automation",
    tags: ["Reviews", "AI", "Reputation", "Customer Service"],
    price: 2490,
    oldPrice: 3490,
    rating: "4.5",
    reviewsCount: 29,
    salesCount: 176,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "15 minutes",
    version: "1.0.2",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "indigo",
    features: [
      "Monitors reviews across platforms",
      "Drafts personalized on-brand replies",
      "Auto-posts low-risk positive replies",
      "Queues negative reviews for approval",
    ],
    requirements: ["Google Business Profile / platform API", "OpenAI API key"],
    setupSteps: ["Import workflow", "Connect review platform accounts", "Set approval rules", "Activate monitoring"],
    included: [{ name: "AI-Review-Response.json", type: "n8n workflow" }],
    workflowSteps: ["New Review Trigger", "Sentiment Check", "AI Reply Draft", "Approval Queue", "Auto-Post"],
    faq: [{ q: "Can negative reviews be auto-published?", a: "By default they are queued for human approval; this is configurable." }],
    reviewSeed: [{ author: "Areeba Nasir", role: "Founder", rating: 4, comment: "Keeps our review responses consistent across three locations." }],
  },
  {
    slug: "appointment-booking-assistant",
    name: "Appointment Booking Assistant",
    tagline: "AI handles scheduling questions and books meetings automatically.",
    description:
      "An AI assistant that answers scheduling questions over chat or WhatsApp, checks your calendar availability, and books confirmed appointments — including reminders and reschedule handling.",
    category: "Business Automation",
    tags: ["Appointments", "Scheduling", "AI", "WhatsApp"],
    price: 3990,
    oldPrice: null,
    rating: "4.7",
    reviewsCount: 51,
    salesCount: 322,
    difficulty: "Intermediate",
    compatibility: "n8n",
    setupTime: "25 minutes",
    version: "1.3.0",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: false,
    isNew: true,
    image: "teal",
    features: [
      "Answers scheduling questions conversationally",
      "Checks live calendar availability",
      "Books and confirms appointments automatically",
      "Sends reminders and handles reschedules",
    ],
    requirements: ["Calendar API (Google/Outlook)", "Chat/WhatsApp channel", "OpenAI API key"],
    setupSteps: ["Import workflow", "Connect calendar", "Connect chat/WhatsApp channel", "Configure availability rules"],
    included: [{ name: "Appointment-Booking-Assistant.json", type: "n8n workflow" }],
    workflowSteps: ["Chat/WhatsApp Trigger", "AI Assistant", "Calendar Check", "Booking Confirmation", "Reminder"],
    faq: [{ q: "Can it handle time zone differences?", a: "Yes, time zones are normalized automatically based on the contact's details." }],
    reviewSeed: [{ author: "Junaid Hussain", role: "Founder", rating: 5, comment: "Eliminated back-and-forth scheduling emails almost entirely." }],
  },
  {
    slug: "rag-knowledge-base-agent",
    name: "RAG Knowledge Base Agent",
    tagline: "A retrieval-augmented AI agent trained on your own documents.",
    description:
      "Build a private AI assistant that answers questions strictly from your own documents — manuals, policies, SOPs — using retrieval-augmented generation. Ideal for internal knowledge bases and customer-facing docs bots.",
    category: "AI Agents",
    tags: ["RAG", "AI", "Knowledge Base", "Vector Database"],
    price: 7500,
    oldPrice: 9990,
    rating: "4.9",
    reviewsCount: 61,
    salesCount: 298,
    difficulty: "Advanced",
    compatibility: "n8n",
    setupTime: "45 minutes",
    version: "2.1.0",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: true,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "violet",
    features: [
      "Indexes your documents into a vector database",
      "Answers strictly from your knowledge base",
      "Cites source documents in every answer",
      "Supports PDF, Notion, and website sources",
    ],
    requirements: ["Vector database (Pinecone/Supabase/Postgres)", "OpenAI or Claude API key"],
    setupSteps: ["Import workflow", "Connect your document sources", "Run the indexing pipeline", "Deploy the chat endpoint"],
    included: [{ name: "RAG-Knowledge-Base-Agent.json", type: "n8n workflow" }, { name: "Vector DB setup guide", type: "guide" }],
    workflowSteps: ["Document Source", "Chunk & Embed", "Vector Store", "Retrieval Agent", "Cited Answer"],
    faq: [{ q: "Which vector databases are supported?", a: "Pinecone, Supabase pgvector, and self-hosted Postgres with pgvector." }],
    reviewSeed: [{ author: "Waleed Anjum", role: "Automation Consultant", rating: 5, comment: "Deployed this for a client's internal SOP bot — works beautifully." }],
  },
  {
    slug: "sales-follow-up-machine",
    name: "Sales Follow-Up Machine",
    tagline: "A full multi-touch AI follow-up system across email and WhatsApp.",
    description:
      "A complete follow-up engine that nurtures leads across email and WhatsApp with AI-personalized touches over a two-week cadence, automatically pausing when a prospect engages and alerting sales reps at the right moment to jump in.",
    category: "Sales Automation",
    tags: ["Sales", "Follow-up", "WhatsApp", "Email", "AI"],
    price: 6990,
    oldPrice: 9500,
    rating: "4.8",
    reviewsCount: 55,
    salesCount: 340,
    difficulty: "Intermediate",
    compatibility: "n8n",
    setupTime: "30 minutes",
    version: "1.7.0",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: false,
    image: "cyan",
    features: [
      "Multi-touch cadence across email + WhatsApp",
      "AI personalizes every touchpoint",
      "Auto-pauses on prospect engagement",
      "Live rep hand-off alerts",
    ],
    requirements: ["Email + WhatsApp channel access", "CRM API", "OpenAI API key"],
    setupSteps: ["Import workflow", "Connect email and WhatsApp channels", "Configure cadence steps", "Connect CRM for hand-off alerts"],
    included: [{ name: "Sales-Follow-Up-Machine.json", type: "n8n workflow" }],
    workflowSteps: ["New Lead", "Cadence Engine", "AI Personalization", "Engagement Check", "Rep Hand-off"],
    faq: [{ q: "Can I add SMS as a channel?", a: "Yes, additional channels can be added as extra branches in the cadence engine." }],
    reviewSeed: [{ author: "Noman Baig", role: "Agency Owner", rating: 5, comment: "This is basically an entire SDR workflow in a box." }],
  },
  {
    slug: "multi-agent-research-system",
    name: "Multi-Agent Research System",
    tagline: "A team of specialized AI agents that collaborate on complex research.",
    description:
      "Orchestrates multiple specialized AI agents — a planner, researchers, a fact-checker, and a writer — that collaborate autonomously to produce comprehensive, well-structured reports on complex topics far beyond what a single prompt can achieve.",
    category: "AI Agents",
    tags: ["AI", "Multi-Agent", "Research", "Advanced"],
    price: 8990,
    oldPrice: 12500,
    rating: "4.9",
    reviewsCount: 39,
    salesCount: 152,
    difficulty: "Advanced",
    compatibility: "n8n",
    setupTime: "50 minutes",
    version: "1.0.0",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: false,
    onSale: true,
    isNew: true,
    image: "indigo",
    features: [
      "Planner agent breaks down the research task",
      "Parallel researcher agents gather evidence",
      "Dedicated fact-checking agent",
      "Writer agent compiles a polished final report",
    ],
    requirements: ["Search API", "OpenAI or Claude API key (multiple calls)", "Vector store (optional)"],
    setupSteps: ["Import workflow", "Connect search + LLM APIs", "Configure agent roles", "Run with a research brief"],
    included: [{ name: "Multi-Agent-Research-System.json", type: "n8n workflow" }, { name: "Agent role prompt pack", type: "prompts" }],
    workflowSteps: ["Planner Agent", "Researcher Agents", "Fact-Checker Agent", "Writer Agent", "Final Report"],
    faq: [{ q: "Is this expensive to run due to multiple LLM calls?", a: "It uses more tokens than a single-agent workflow; we recommend budgeting API usage accordingly." }],
    reviewSeed: [{ author: "Sarmad Khalid", role: "Automation Consultant", rating: 5, comment: "The most advanced workflow in the catalog — genuinely impressive output quality." }],
  },
  {
    slug: "free-ai-email-classifier",
    name: "Free AI Email Classifier",
    tagline: "Automatically label and route inbox emails using AI.",
    description:
      "A free starter workflow that classifies incoming emails into categories (sales, support, spam, urgent) using AI and applies labels or routes them to the right folder automatically. A great first workflow to learn n8n + AI basics.",
    category: "Business Automation",
    tags: ["AI", "Email", "Free", "Beginner"],
    price: 0,
    oldPrice: null,
    rating: "4.6",
    reviewsCount: 203,
    salesCount: 3120,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "10 minutes",
    version: "1.0.0",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: true,
    onSale: false,
    isNew: false,
    image: "teal",
    features: [
      "Classifies emails into custom categories",
      "Applies labels automatically",
      "Routes urgent emails for fast follow-up",
      "Simple to extend with your own categories",
    ],
    requirements: ["Email API access (Gmail/Outlook)", "OpenAI API key"],
    setupSteps: ["Import workflow", "Connect your inbox", "Define categories", "Activate"],
    included: [{ name: "Free-Email-Classifier.json", type: "n8n workflow" }],
    workflowSteps: ["New Email", "AI Classifier", "Label Application", "Route/Notify"],
    faq: [{ q: "Is this workflow really free forever?", a: "Yes, this is a permanently free demo workflow available to all members." }],
    reviewSeed: [{ author: "Imran Wasti", role: "Freelancer", rating: 5, comment: "Perfect first workflow to understand how n8n + AI nodes work together." }],
  },
  {
    slug: "free-lead-capture-workflow",
    name: "Free Lead Capture Workflow",
    tagline: "Capture web form leads and notify your team instantly — free.",
    description:
      "A simple, free workflow that captures leads from any web form or webhook, cleans the data, stores it in a spreadsheet, and instantly notifies your team by email or Slack. A perfect foundation to build more advanced lead workflows on top of.",
    category: "Marketing Automation",
    tags: ["Leads", "Free", "Webhook", "Beginner"],
    price: 0,
    oldPrice: null,
    rating: "4.5",
    reviewsCount: 167,
    salesCount: 2890,
    difficulty: "Beginner",
    compatibility: "n8n",
    setupTime: "10 minutes",
    version: "1.0.1",
    creator: "FlowForge Studio",
    featured: false,
    bestseller: false,
    isFree: true,
    onSale: false,
    isNew: false,
    image: "cyan",
    features: [
      "Captures leads from any web form/webhook",
      "Cleans and validates submitted data",
      "Stores leads in Google Sheets",
      "Sends instant team notifications",
    ],
    requirements: ["Webhook-capable form", "Google Sheets access"],
    setupSteps: ["Import workflow", "Point your form to the webhook URL", "Connect Google Sheets", "Activate notifications"],
    included: [{ name: "Free-Lead-Capture.json", type: "n8n workflow" }],
    workflowSteps: ["Webhook Trigger", "Data Cleaning", "Sheet Storage", "Team Notification"],
    faq: [{ q: "Can I upgrade this later to include AI scoring?", a: "Yes, it pairs perfectly with our AI WhatsApp Lead Qualifier as a next step." }],
    reviewSeed: [{ author: "Sadia Yousaf", role: "Founder", rating: 4, comment: "Simple, reliable, and free — exactly what I needed to get started." }],
  },
];

async function main() {
  console.log("Seeding FlowForge AI marketplace demo data...");

  await db.execute(sql`truncate table order_items, orders, reviews, coupons, products restart identity cascade`);

  for (const item of catalog) {
    const { reviewSeed, ...productData } = item;
    const [inserted] = await db.insert(products).values(productData).returning({ id: products.id });

    if (reviewSeed.length) {
      await db.insert(reviews).values(
        reviewSeed.map((r) => ({
          productId: inserted.id,
          author: r.author,
          role: r.role,
          rating: r.rating,
          comment: r.comment,
        }))
      );
    }
  }

  await db.insert(coupons).values([
    { code: "WELCOME20", percent: 20, active: true, expiresAt: null },
    { code: "AUTOMATE10", percent: 10, active: true, expiresAt: null },
    { code: "EXPIRED5", percent: 5, active: false, expiresAt: new Date("2024-01-01") },
  ]);

  console.log(`Seeded ${catalog.length} products, reviews, and demo coupons.`);
  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
